import "./globals.css";
import Link from "next/link";

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header>
          <nav>
            <Link className="nav-link" href="/">
              Homepage
            </Link>

            <div>
              <Link className="nav-link" href="/register">
                Register
              </Link>

              <Link className="nav-link" href="/dashboard">
                Dashboard
              </Link>
            </div>
          </nav>
        </header>
        <main>{children}</main>

        <footer>Footer</footer>
      </body>
    </html>
  );
}
